gitlab-server:
  ports:
  - 22:22/tcp
  - 80:80/tcp
  environment:
    GITLAB_SSH_PORT: ${gitlab_ssh_port}
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:8.6.6-ce.0
  volumes_from:
  - gitlab-data

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:8.6.6-ce.0
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab

